using System.Net.Http.Headers;

namespace MssBase.UI.HttpClients
{
    public class BearerTokenHandler : DelegatingHandler
    {
        // TODO: replace with the signed-in user's token.
        private const string Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiSW50ZWdyYXRpb25UZXN0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJJbnRlZ3JhdGlvblRlc3RAZXhhbXBsZS5jb20iLCJhcHBsaWNhdGlvbnMiOlsiTVNTIFNlY3VyaXR5Il0sInJvbGVzIjpbXSwicGVybWlzc2lvbnMiOlsiVGVzdCBQZXJtaXNzaW9uIDEiLCJUZXN0IFBlcm1pc3Npb24gMiIsIlRlc3QgUGVybWlzc2lvbiAzIiwiVGVzdCBQZXJtaXNzaW9uIDQiLCJUZXN0IFBlcm1pc3Npb24gNSIsIkFwcGxpY2F0aW9uUmVhZCIsIkFwcGxpY2F0aW9uSW5zZXJ0IiwiQXBwbGljYXRpb25VcGRhdGUiLCJBcHBsaWNhdGlvbkRlbGV0ZSIsIlVzZXJSZWFkIiwiVXNlckluc2VydCIsIlVzZXJVcGRhdGUiLCJVc2VyRGVsZXRlIiwiVXNlclJlc2V0UGFzc3dvcmQiLCJVc2VyQ2hhbmdlUGFzc3dvcmQiLCJVc2VyUGFzc3dvcmRDaGFuZ2VIaXN0b3J5UmVhZCIsIkFwcGxpY2F0aW9uVXNlclJlYWQiLCJBcHBsaWNhdGlvblVzZXJJbnNlcnQiLCJBcHBsaWNhdGlvblVzZXJVcGRhdGUiLCJBcHBsaWNhdGlvblVzZXJEZWxldGUiLCJBcHBsaWNhdGlvblVzZXJSZXNldFBhc3N3b3JkIiwiQXBwbGljYXRpb25Vc2VyQ2hhbmdlUGFzc3dvcmQiLCJBcHBsaWNhdGlvblVzZXJQYXNzd29yZENoYW5nZUhpc3RvcnlSZWFkIiwiQXBwbGljYXRpb25Vc2VyUGVybWlzc2lvblJlYWQiLCJBcHBsaWNhdGlvblVzZXJQZXJtaXNzaW9uSW5zZXJ0IiwiQXBwbGljYXRpb25Vc2VyUGVybWlzc2lvblVwZGF0ZSIsIkFwcGxpY2F0aW9uVXNlclBlcm1pc3Npb25EZWxldGUiLCJBcHBsaWNhdGlvblVzZXJSb2xlUmVhZCIsIkFwcGxpY2F0aW9uVXNlclJvbGVJbnNlcnQiLCJBcHBsaWNhdGlvblVzZXJSb2xlVXBkYXRlIiwiQXBwbGljYXRpb25Vc2VyUm9sZURlbGV0ZSIsIlBlcm1pc3Npb25SZWFkIiwiUGVybWlzc2lvbkluc2VydCIsIlBlcm1pc3Npb25VcGRhdGUiLCJQZXJtaXNzaW9uRGVsZXRlIiwiUm9sZVJlYWQiLCJSb2xlSW5zZXJ0IiwiUm9sZVVwZGF0ZSIsIlJvbGVEZWxldGUiLCJSb2xlUGVybWlzc2lvblJlYWQiLCJSb2xlUGVybWlzc2lvbkluc2VydCIsIlJvbGVQZXJtaXNzaW9uVXBkYXRlIiwiUm9sZVBlcm1pc3Npb25EZWxldGUiXSwiZXhwIjoxNzkxMzM4MjExLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MjE3IiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTIxNyJ9.v6ehBkhYsud4WxbOiTuNwqLZIyUmgBzGjSHH4SWdWG0";

        protected override Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request,
            CancellationToken cancellationToken)
        {
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", Token);
            return base.SendAsync(request, cancellationToken);
        }
    }
}
