info:
  name: Delete ApplicationUserRole
  type: http
  seq: 1

http:
  method: DELETE
  url: "{{BaseUrl}}/Security/ApplicationUserRole/:ApplicationUserRoleId"
  params:
    - name: ApplicationUserRoleId
      value: ""
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5