info:
  name: Delete ApplicationUserPermission
  type: http
  seq: 1

http:
  method: DELETE
  url: "{{BaseUrl}}/Security/ApplicationUserPermission/:ApplicationUserPermissionId"
  params:
    - name: ApplicationUserPermissionId
      value: ""
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
