info:
  name: Get ApplicationUserRole By Id
  type: http
  seq: 1

http:
  method: GET
  url: "{{BaseUrl}}/Security/ApplicationUserRole/:ApplicationUserRoleId"
  params:
    - name: includeInactive
      value: "true"
      type: query
      disabled: true
    - name: IncludeRelated
      value: "true"
      type: query
      disabled: true
    - name: IncludeReadOnly
      value: "true"
      type: query
      disabled: true
    - name: ApplicationUserRoleId
      value: ""
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
