// <auto-generated />
using System;
using Data.Security.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Security.Migrations
{
    [DbContext(typeof(SecurityDBContext))]
    [Migration("20260314212819_3_14_26_ApplicationUserRole_Take2")]
    partial class _3_14_26_ApplicationUserRole_Take2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Security.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedOn")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.HasKey("ApplicationId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Application_Name");

                    b.ToTable("Application", (string)null);

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            Active = true,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enterprise Dispatch and Monitoring System for Logistic Operations",
                            Name = "EOS",
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ApplicationId = 2,
                            Active = true,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enterprise Financial System for Processing Pricing & Commissions",
                            Name = "EPC",
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ApplicationId = 3,
                            Active = true,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Enterprise User Permission Management System",
                            Name = "EBS",
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ApplicationId = 4,
                            Active = true,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Interchange Configuration Tool",
                            Name = "Bet-t",
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ApplicationId = 5,
                            Active = true,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Agent Analytics / Reporting Portal",
                            Name = "MyPortfolio",
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ApplicationId = 6,
                            Active = true,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Agent Management Platform",
                            Name = "AIME",
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Data.Security.Models.ApplicationUser", b =>
                {
                    b.Property<int>("ApplicationUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationUserId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedOn")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<short?>("FailedPasswordAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("FirstName")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("LastLockoutDate")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("LastPasswordChangeDate")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("Password")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.HasKey("ApplicationUserId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_ApplicationUser_Email");

                    b.ToTable("ApplicationUser", (string)null);

                    b.HasData(
                        new
                        {
                            ApplicationUserId = 1,
                            Active = true,
                            ApplicationId = 2,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dkm8923@gmail.com",
                            FirstName = "Dan",
                            LastName = "Mauk",
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ApplicationUserId = 2,
                            Active = true,
                            ApplicationId = 1,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thompsonswartz@gmail.com",
                            FirstName = "Rachel",
                            LastName = "Thompson",
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Data.Security.Models.ApplicationUserPermission", b =>
                {
                    b.Property<int>("ApplicationUserPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationUserPermissionId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedOn")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.HasKey("ApplicationUserPermissionId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("ApplicationId", "ApplicationUserId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ApplicationUserPermission_ApplicationId_ApplicationUserId_PermissionId");

                    b.ToTable("ApplicationUserPermission", (string)null);

                    b.HasData(
                        new
                        {
                            ApplicationUserPermissionId = 1,
                            Active = true,
                            ApplicationId = 2,
                            ApplicationUserId = 1,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 2,
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Data.Security.Models.ApplicationUserRole", b =>
                {
                    b.Property<int>("ApplicationUserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationUserRoleId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedOn")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.HasKey("ApplicationUserRoleId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ApplicationId", "ApplicationUserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ApplicationUserRole_ApplicationId_ApplicationUserId_RoleId");

                    b.ToTable("ApplicationUserRole", (string)null);
                });

            modelBuilder.Entity("Data.Security.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedOn")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.HasKey("PermissionId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Permission_Name");

                    b.ToTable("Permission", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            Active = true,
                            ApplicationId = 1,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Default Base Permission for EOS Application",
                            Name = "EosDefaultUser",
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PermissionId = 2,
                            Active = true,
                            ApplicationId = 2,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Default Base Permission for EPC Application",
                            Name = "EpcDefaultUser",
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PermissionId = 3,
                            Active = true,
                            ApplicationId = 2,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Default Base Permission for Commission Reviewer UI / Services",
                            Name = "CommissionReviewer",
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PermissionId = 4,
                            Active = true,
                            ApplicationId = 2,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Permission for Allowing Access to Change Contractor on Commission Reviewer UI / Services",
                            Name = "CommissionReviewerChangeContractor",
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PermissionId = 5,
                            Active = true,
                            ApplicationId = 2,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Permission for Adjusting Contractor Rates on Commission Reviewer UI / Services",
                            Name = "CommissionReviewerAdjustRate",
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Data.Security.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedOn")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.HasKey("RoleId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Role_Name");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Active = true,
                            ApplicationId = 2,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Super User Role for EPC Application",
                            Name = "DataAnalyst",
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 2,
                            Active = true,
                            ApplicationId = 2,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Read Only Role for EPC Application",
                            Name = "OfficeUser",
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Data.Security.Models.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermissionId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedOn")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasPrecision(2)
                        .HasColumnType("datetime2(2)");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ApplicationId", "RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_RolePermission_ApplicationId_RoleId_PermissionId");

                    b.ToTable("RolePermission", (string)null);

                    b.HasData(
                        new
                        {
                            RolePermissionId = 1,
                            Active = true,
                            ApplicationId = 2,
                            CreatedBy = "MssBase.Service",
                            CreatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PermissionId = 2,
                            RoleId = 1,
                            UpdatedBy = "MssBase.Service",
                            UpdatedOn = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Data.Security.Models.ApplicationUser", b =>
                {
                    b.HasOne("Data.Security.Models.Application", "Application")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationUser_Application");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Data.Security.Models.ApplicationUserPermission", b =>
                {
                    b.HasOne("Data.Security.Models.Application", "Application")
                        .WithMany("ApplicationUserPermissions")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationUserPermission_Application");

                    b.HasOne("Data.Security.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserPermissions")
                        .HasForeignKey("ApplicationUserId")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationUserPermission_User");

                    b.HasOne("Data.Security.Models.Permission", "Permission")
                        .WithMany("ApplicationUserPermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationUserPermission_Permission");

                    b.Navigation("Application");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Data.Security.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("Data.Security.Models.Application", "Application")
                        .WithMany("ApplicationUserRoles")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationUserRole_Application");

                    b.HasOne("Data.Security.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserRoles")
                        .HasForeignKey("ApplicationUserId")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationUserRole_User");

                    b.HasOne("Data.Security.Models.Role", "Role")
                        .WithMany("ApplicationUserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationUserRole_Role");

                    b.Navigation("Application");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Data.Security.Models.Permission", b =>
                {
                    b.HasOne("Data.Security.Models.Application", "Application")
                        .WithMany("Permissions")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_Permission_Application");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Data.Security.Models.Role", b =>
                {
                    b.HasOne("Data.Security.Models.Application", "Application")
                        .WithMany("Roles")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_Role_Application");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Data.Security.Models.RolePermission", b =>
                {
                    b.HasOne("Data.Security.Models.Application", "Application")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Application");

                    b.HasOne("Data.Security.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Permission");

                    b.HasOne("Data.Security.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Role");

                    b.Navigation("Application");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Data.Security.Models.Application", b =>
                {
                    b.Navigation("ApplicationUserPermissions");

                    b.Navigation("ApplicationUserRoles");

                    b.Navigation("ApplicationUsers");

                    b.Navigation("Permissions");

                    b.Navigation("RolePermissions");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Data.Security.Models.ApplicationUser", b =>
                {
                    b.Navigation("ApplicationUserPermissions");

                    b.Navigation("ApplicationUserRoles");
                });

            modelBuilder.Entity("Data.Security.Models.Permission", b =>
                {
                    b.Navigation("ApplicationUserPermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Data.Security.Models.Role", b =>
                {
                    b.Navigation("ApplicationUserRoles");

                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
